### ISSUE TITLE
Option to reset UI element positions.

### ISSUE THREAD

**Issue by SillyEcho** [chalkos/RepairMe#20] opened 2022-01-11 23:28 UTC
For some reason my percentage counter reset to the upper left to the window and cannot be moved. Having an option to reset its position to the default would be nice.

**Comment by chalkos** [comment] 2022-01-24 18:41
Possible duplicate of #4

**Comment by chalkos** [comment] 2022-04-15 06:38
A fix for this will be in testing when this PR is accepted https://github.com/goatcorp/DalamudPlugins/pull/2301
Note that loading this version will erase your position settings and you'll need to reposition everything again using the new position sliders.
This doesn't add a reset position button, but allows you to specify where you want things via setting their X/Y position

**Closed by chalkos** 2022-04-15 06:38 UTC
Labels: suggestion

**Comment by chalkos** [comment] 2022-04-16 08:13
https://github.com/goatcorp/DalamudPlugins/pull/2337
this one no longer reset position settings
