### ISSUE TITLE
Position reset when restarting the game

### ISSUE THREAD

**Issue by Makpptfox** [chalkos/RepairMe#12] opened 2021-11-17 16:50 UTC
Hello!

I'm coming here without a clue as to why I have this issue, so here it is : When I place the bar when I want it to be, restart the game, it reset itself on the top left. I did nothing, quitted the game the right way and made sure to save beforehand.
Here a clear picture of the issue.

Before restart : 
https://i.imgur.com/QQuBdwr.png
After : 
https://i.imgur.com/iWz9TOD.png

Would you have any idea as to why it is happening?

Regards.

**Comment by chalkos** [comment] 2021-11-20 11:41
That's a weird one. what happens if you disable it and reinstall?

**Comment by Makpptfox** [comment] 2021-11-20 18:17
Nothing happens, it stay in the position it was when I disabled it.

So if I had replaced it in the center of my screen it reappear here, if I had restarted the game it reappear in the top left.

But once I restart the game it's always the same, it as if the top left was a "default" position it chooses when some kind of issues occure.

**Comment by Tysaki** [comment] 2022-01-08 05:27
for me this also happens when i switch from fullscreen to borderless. if i switch back it stays in the scuffed position it was put while in borderless. hope this info helps

**Comment by SillyEcho** [comment] 2022-01-12 22:05
I can confirm this happens. For me it happened with the durability percentage. It is stuck in the upper left corner and can't be moved.

The other UI elements are fine.

**Comment by Almeris** [comment] 2022-01-16 11:21
It happens to mine too. All the UI components do reset each time I restart the game, all stacked in the upper-left corner of the screen. Furthermore, the configuration always shows up with the "Testing mode" enabled.
![image](https://user-images.githubusercontent.com/9740982/149657724-80c58dd6-d96b-4dfc-8ff6-9ef2cc519827.png)

If it helps, I play the game as borderless window on a 4k resolution TV.

**Comment by pigsflew** [comment] 2022-04-05 21:39
I have a similar problem due to having a laptop with a different screen size than my monitor, so when something happens to upset the connection to the monitor, the position gets all messed up.

Would it be possible to have the position configuration store a percentage of monitor X/Y instead of an exact pixel point from top left?

Other possibilities include using a different "anchor point"--that is, storing the position as an offset from 0, x/y, or middle--like this:

Position: `X = 0 [Left]) + 500px`, `Y = (1080 [Bottom]) - 100px`

That way, no matter the size of the monitor, it'd always be a position very close to where I want it.

**Comment by chalkos** [comment] 2022-04-06 02:38
I'll probably fix this by saving multiple positions depending on the resolution. I tried using percentages and it wasn't working as expected.

you'd have to reposition everything for each resolution (only once), but then everything would stay in place when changing resolutions. and it would allow for pixel perfect placements, which doesn't work well with percent-based positioning

**Comment by chalkos** [comment] 2022-04-15 06:36
A possible fix for this will be in testing when this PR is accepted https://github.com/goatcorp/DalamudPlugins/pull/2301
Note that loading this version will erase your position settings and you'll need to reposition everything again using the new position sliders.

**Comment by chalkos** [comment] 2022-04-15 06:40
Closing this for now and I'll wait for the feedback on the testing version

**Closed by chalkos** 2022-04-15 06:40 UTC
Labels: bug

**Comment by chalkos** [comment] 2022-04-16 08:13
https://github.com/goatcorp/DalamudPlugins/pull/2337
this one no longer reset position settings
